-- SOLUTION TEMPORAIRE: Désactiver RLS sur toutes les tables pour débloquer l'application
-- ATTENTION: Ceci désactive la sécurité - à utiliser temporairement uniquement

-- Tables principales
ALTER TABLE IF EXISTS profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS versions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS steps DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_version_progress DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS learner_progress DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS trainer_learner_links DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS contact_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS faq_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS error_reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS app_images DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS task_categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS learner_visibility DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS images_metadata DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS trainer_licenses DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS license_assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS stripe_transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS contributor_revenue DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS exercise_modification_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS questionnaire_questions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS questionnaire_responses DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS questionnaire_attempts DISABLE ROW LEVEL SECURITY;

-- Vérification: lister les tables avec RLS encore activé
SELECT 
  schemaname,
  tablename,
  rowsecurity
FROM pg_tables
WHERE schemaname = 'public' 
  AND rowsecurity = true
ORDER BY tablename;
