-- ============================================================================
-- MIGRATION: Add Contributor Revenue Tracking System
-- ============================================================================
-- This migration creates tables to track sales and revenue generated by
-- contributors' exercises and images

-- Create table for tracking exercise sales
CREATE TABLE IF NOT EXISTS contributor_exercise_sales (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  exercise_id UUID NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  contributor_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  version_id UUID REFERENCES versions(id) ON DELETE CASCADE,
  buyer_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  price_cents INTEGER NOT NULL DEFAULT 1000, -- Price in cents (default €10)
  purchase_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Create table for tracking image sales
CREATE TABLE IF NOT EXISTS contributor_image_sales (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  image_id UUID NOT NULL REFERENCES images_metadata(id) ON DELETE CASCADE,
  contributor_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  buyer_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  price_cents INTEGER NOT NULL DEFAULT 500, -- Price in cents (default €5)
  purchase_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Create view for contributor revenue summary
CREATE OR REPLACE VIEW contributor_revenue_summary AS
SELECT 
  p.id as contributor_id,
  p.first_name,
  p.last_name,
  p.email,
  COALESCE(exercise_stats.total_sales, 0) as exercise_sales_count,
  COALESCE(exercise_stats.total_revenue, 0) as exercise_revenue_cents,
  COALESCE(image_stats.total_sales, 0) as image_sales_count,
  COALESCE(image_stats.total_revenue, 0) as image_revenue_cents,
  COALESCE(exercise_stats.total_revenue, 0) + COALESCE(image_stats.total_revenue, 0) as total_revenue_cents,
  COALESCE(exercise_stats.total_sales, 0) + COALESCE(image_stats.total_sales, 0) as total_sales_count,
  FLOOR((COALESCE(exercise_stats.total_revenue, 0) + COALESCE(image_stats.total_revenue, 0)) / 100000) as milestone_count -- €1000 milestones
FROM profiles p
LEFT JOIN (
  SELECT 
    contributor_id,
    COUNT(*) as total_sales,
    SUM(price_cents) as total_revenue
  FROM contributor_exercise_sales
  GROUP BY contributor_id
) exercise_stats ON p.id = exercise_stats.contributor_id
LEFT JOIN (
  SELECT 
    contributor_id,
    COUNT(*) as total_sales,
    SUM(price_cents) as total_revenue
  FROM contributor_image_sales
  GROUP BY contributor_id
) image_stats ON p.id = image_stats.contributor_id
WHERE p.role = 'contributeur' OR p.role = 'contributor';

-- Create indices for better performance
CREATE INDEX IF NOT EXISTS idx_contributor_exercise_sales_contributor_id 
  ON contributor_exercise_sales(contributor_id);
CREATE INDEX IF NOT EXISTS idx_contributor_exercise_sales_exercise_id 
  ON contributor_exercise_sales(exercise_id);
CREATE INDEX IF NOT EXISTS idx_contributor_image_sales_contributor_id 
  ON contributor_image_sales(contributor_id);
CREATE INDEX IF NOT EXISTS idx_contributor_image_sales_image_id 
  ON contributor_image_sales(image_id);

-- ============================================================================
-- RLS Policies
-- ============================================================================

-- Enable RLS on both tables
ALTER TABLE contributor_exercise_sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE contributor_image_sales ENABLE ROW LEVEL SECURITY;

-- Contributors can view their own sales
CREATE POLICY "Contributors view own exercise sales"
  ON contributor_exercise_sales FOR SELECT
  USING (auth.uid() = contributor_id);

CREATE POLICY "Contributors view own image sales"
  ON contributor_image_sales FOR SELECT
  USING (auth.uid() = contributor_id);

-- Admin can view all sales
CREATE POLICY "Admin view all exercise sales"
  ON contributor_exercise_sales FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'administrateur'
    )
  );

CREATE POLICY "Admin view all image sales"
  ON contributor_image_sales FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'administrateur'
    )
  );

-- Admin can insert sales
CREATE POLICY "Admin insert exercise sales"
  ON contributor_exercise_sales FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'administrateur'
    )
  );

CREATE POLICY "Admin insert image sales"
  ON contributor_image_sales FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'administrateur'
    )
  );

-- ============================================================================
-- Success Message
-- ============================================================================
SELECT 'Contributor Revenue Tracking System successfully created!' as status;
