-- Migration: Ajouter support des variantes de mots au lexique
-- Permet d'associer glisse, glisser, glissement à la même définition

-- 1. Ajouter colonne variants à la table glossary
ALTER TABLE glossary
ADD COLUMN IF NOT EXISTS variants TEXT[] DEFAULT ARRAY[]::TEXT[];

-- Ajouter un commentaire explicatif
COMMENT ON COLUMN glossary.variants IS 'Variantes du terme (ex: [glisse, glisser, glissement])';

-- 2. Créer une table de variantes pour plus de flexibilité (optionnel)
CREATE TABLE IF NOT EXISTS glossary_variants (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  glossary_id BIGINT NOT NULL REFERENCES glossary(id) ON DELETE CASCADE,
  variant_word TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT NOW(),
  
  CONSTRAINT glossary_variants_glossary_id_fkey FOREIGN KEY (glossary_id) REFERENCES glossary(id) ON DELETE CASCADE
);

-- Index pour recherche rapide
CREATE INDEX IF NOT EXISTS idx_glossary_variants_variant_word ON glossary_variants(variant_word);
CREATE INDEX IF NOT EXISTS idx_glossary_variants_glossary_id ON glossary_variants(glossary_id);

-- 3. Mettre à jour les termes existants avec leurs variantes
-- Terme: Glissement
UPDATE glossary 
SET variants = ARRAY['glisse', 'glisser', 'glissant', 'glissements']
WHERE term = 'Glissement' AND is_active = true;

-- Insérer les variantes dans la table associée
INSERT INTO glossary_variants (glossary_id, variant_word)
SELECT id, variant FROM glossary g, UNNEST(g.variants) as variant
WHERE g.term = 'Glissement'
ON CONFLICT (variant_word) DO NOTHING;

-- Terme: Scroll (variantes: scroller, scrolling)
UPDATE glossary 
SET variants = ARRAY['scroller', 'scrolling', 'scroll']
WHERE term = 'Scroll' AND is_active = true;

INSERT INTO glossary_variants (glossary_id, variant_word)
SELECT id, variant FROM glossary g, UNNEST(g.variants) as variant
WHERE g.term = 'Scroll'
ON CONFLICT (variant_word) DO NOTHING;

-- Terme: Paramètres (variantes: paramètre, paramétrer, paramétrages)
UPDATE glossary 
SET variants = ARRAY['paramètre', 'paramétrer', 'paramétrages', 'paramétrés']
WHERE term = 'Paramètres' AND is_active = true;

INSERT INTO glossary_variants (glossary_id, variant_word)
SELECT id, variant FROM glossary g, UNNEST(g.variants) as variant
WHERE g.term = 'Paramètres'
ON CONFLICT (variant_word) DO NOTHING;

-- Terme: Icônes (variantes: icône)
UPDATE glossary 
SET variants = ARRAY['icône', 'icones']
WHERE term = 'Icônes' AND is_active = true;

INSERT INTO glossary_variants (glossary_id, variant_word)
SELECT id, variant FROM glossary g, UNNEST(g.variants) as variant
WHERE g.term = 'Icônes'
ON CONFLICT (variant_word) DO NOTHING;

-- Terme: Bouton Power (variantes: boutons power, bouton puissance)
UPDATE glossary 
SET variants = ARRAY['boutons power', 'bouton puissance', 'puissance', 'power']
WHERE term = 'Bouton Power' AND is_active = true;

INSERT INTO glossary_variants (glossary_id, variant_word)
SELECT id, variant FROM glossary g, UNNEST(g.variants) as variant
WHERE g.term = 'Bouton Power'
ON CONFLICT (variant_word) DO NOTHING;

-- Terme: Volume (variantes: augmenter, diminuer, sons, audio)
UPDATE glossary 
SET variants = ARRAY['augmenter', 'diminuer', 'sons', 'audio', 'bruit']
WHERE term = 'Volume' AND is_active = true;

INSERT INTO glossary_variants (glossary_id, variant_word)
SELECT id, variant FROM glossary g, UNNEST(g.variants) as variant
WHERE g.term = 'Volume'
ON CONFLICT (variant_word) DO NOTHING;

-- Terme: Notification (variantes: notifications, notifier, alertes, alerte)
UPDATE glossary 
SET variants = ARRAY['notifications', 'notifier', 'alertes', 'alerte', 'messages']
WHERE term = 'Notification' AND is_active = true;

INSERT INTO glossary_variants (glossary_id, variant_word)
SELECT id, variant FROM glossary g, UNNEST(g.variants) as variant
WHERE g.term = 'Notification'
ON CONFLICT (variant_word) DO NOTHING;

-- Terme: Application (variantes: appli, logiciel, programme, apps)
UPDATE glossary 
SET variants = ARRAY['appli', 'applis', 'logiciel', 'logiciels', 'programme', 'programmes', 'apps', 'software']
WHERE term = 'Application' AND is_active = true;

INSERT INTO glossary_variants (glossary_id, variant_word)
SELECT id, variant FROM glossary g, UNNEST(g.variants) as variant
WHERE g.term = 'Application'
ON CONFLICT (variant_word) DO NOTHING;

-- Terme: Écran d'accueil (variantes: accueil, écran, home, écrans)
UPDATE glossary 
SET variants = ARRAY['accueil', 'écran', 'home', 'écrans', 'd''accueil']
WHERE term = 'Écran d''accueil' AND is_active = true;

INSERT INTO glossary_variants (glossary_id, variant_word)
SELECT id, variant FROM glossary g, UNNEST(g.variants) as variant
WHERE g.term = 'Écran d''accueil'
ON CONFLICT (variant_word) DO NOTHING;

-- Terme: Défilement (variantes: dérouler, scroller, faire défiler, déroulé, défileuse)
UPDATE glossary 
SET variants = ARRAY['dérouler', 'scroller', 'faire défiler', 'déroulé', 'défileuse', 'déroulable']
WHERE term = 'Défilement' AND is_active = true;

INSERT INTO glossary_variants (glossary_id, variant_word)
SELECT id, variant FROM glossary g, UNNEST(g.variants) as variant
WHERE g.term = 'Défilement'
ON CONFLICT (variant_word) DO NOTHING;

-- 4. Créer une vue pour faciliter la recherche
CREATE OR REPLACE VIEW glossary_with_variants AS
SELECT 
  g.id,
  g.term,
  g.definition,
  g.example,
  g.category,
  g.related_terms,
  g.variants,
  g.is_active,
  g.created_at,
  COALESCE(
    ARRAY_AGG(DISTINCT gv.variant_word) FILTER (WHERE gv.variant_word IS NOT NULL),
    ARRAY[]::TEXT[]
  ) as all_variants
FROM glossary g
LEFT JOIN glossary_variants gv ON g.id = gv.glossary_id
WHERE g.is_active = true
GROUP BY g.id, g.term, g.definition, g.example, g.category, g.related_terms, g.variants, g.is_active, g.created_at;

-- 5. RLS pour la table variants (lecture seule, modification admin)
ALTER TABLE glossary_variants ENABLE ROW LEVEL SECURITY;

CREATE POLICY "glossary_variants_select_public" ON glossary_variants
  FOR SELECT USING (true);

CREATE POLICY "glossary_variants_insert_admin" ON glossary_variants
  FOR INSERT 
  WITH CHECK (
    (auth.jwt() ->> 'role')::text = 'admin' OR
    EXISTS (
      SELECT 1 FROM raw_user_meta_data rumd
      WHERE rumd.user_id = auth.uid()
        AND rumd.role = 'admin'
    )
  );

CREATE POLICY "glossary_variants_update_admin" ON glossary_variants
  FOR UPDATE 
  USING (
    (auth.jwt() ->> 'role')::text = 'admin' OR
    EXISTS (
      SELECT 1 FROM raw_user_meta_data rumd
      WHERE rumd.user_id = auth.uid()
        AND rumd.role = 'admin'
    )
  );

CREATE POLICY "glossary_variants_delete_admin" ON glossary_variants
  FOR DELETE 
  USING (
    (auth.jwt() ->> 'role')::text = 'admin' OR
    EXISTS (
      SELECT 1 FROM raw_user_meta_data rumd
      WHERE rumd.user_id = auth.uid()
        AND rumd.role = 'admin'
    )
  );

-- 6. Affiche résumé
SELECT 'Variantes ajoutées:' as status,
  COUNT(DISTINCT glossary_id) as nombre_termes,
  COUNT(*) as total_variantes
FROM glossary_variants;

-- Affiche les termes avec variantes
SELECT term, variants, (SELECT COUNT(*) FROM glossary_variants WHERE glossary_id = g.id) as nb_variantes
FROM glossary g
WHERE is_active = true
  AND (variants IS NOT NULL AND array_length(variants, 1) > 0)
ORDER BY term;
